CREATE TABLE stop (
	id int not null primary key,
	bicycle_cage boolean default false,
	bicycle_lockers int default 0,
	bicycle_racks int default 0,
	car_parking int default 0,
	escalator boolean default false,
	hearing_loop boolean default false,
	latitude float (9,6),
	lift boolean default false,
	lighting boolean default false,
	locality text,
	lockers int default 0,
	longitude float (9,6),
	map_ref text,
	municipiality text,
	municipiality_id int,
	myki_checks boolean default false,
	myki_machines boolean default false,
	phone_feedback text,
	phone_station text,
	postcode int,
	public_phone boolean default false,
	public_toilet boolean default false,
	seating boolean default false,
	staff_hours text,
	stairs boolean default false,
	street text,
	tactile_paths boolean default false,
	taxi_rank boolean default false,
	transport_type text,
	vline_bookings boolean default false,
	waiting_area_indoor boolean default false,
	waiting_area_sheltered boolean default false,
	wheelchair_accessible boolean default false,
	zone text,
	zone_id int
);
